#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

void abc(void)
{
    while (1)
        printf("In abc...\n");
}

void def(void)
{
    printf("In def...\n");
}

int main()
{
    printf("Hello...\n");
    atexit(abc);
    atexit(def);
    printf("Hai...\n");
    sleep(10);
    printf("Bye...\n");
    exit(0); // Use exit(), not _exit()
}

output:
Hello...
Hai...
|AFTER 10 SECONDS|
Bye...
In def...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
In abc...
...
...
...

SUMMARY:
Program starts, prints "Hello...".
Registers abc() and def() with atexit().
Prints "Hai...".
Waits for 10 seconds.
Prints "Bye...".
Calls exit(0); → program ends normally.
Because of atexit():
def() runs → prints "In def...".
Then abc() runs → prints "In abc..." again and again forever.
So the program never fully stops because abc() is an infinite loop.


